### ISSUE TITLE
알림기능(오픈,D-1)

### ISSUE THREAD

**Issue by BlueUmb** [Purplaying-Main/Purplaying#16]
관심펀딩 중 오픈예정(comingday ==1) or 종료예정(dday == 1)인 펀딩 출력
알림영역에 멘트 다르게 출력

12/13 예외일때 '오픈예정이거나 종료예정인 펀딩이없습니다' 출력 오류. 수정필요

**Comment by he22ra** [comment]
12/19 tb_like, tb_product INNER JOIN. >> 찜하기 클릭시 tb_alarm DB 생성. 
오픈D-1, 마감D-1 알림탭에 출력완료
+ '확인' 클릭시 뱃지 삭제 및 아래 열로 정렬 변경 >> ajax 수정 중(12/19)
